---
- hosts: droplets

  remote_user: ansible  
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
